const wordData = [

  { word: "社区", pinyin: "shequ", meaning: "community; neighborhood" },
  { word: "白天", pinyin: "baitian", meaning: "daytime" },
  { word: "被", pinyin: "bei", meaning: "by (passive marker)" },
  { word: "小偷", pinyin: "xiaotou", meaning: "thief" },
  { word: "偷", pinyin: "tou", meaning: "to steal" },
  { word: "负责", pinyin: "fuze", meaning: "to be responsible for; in charge of" },
  { word: "安全", pinyin: "anquan", meaning: "safety; safe" },
  { word: "大门", pinyin: "damen", meaning: "main gate; front door" },
  { word: "草地", pinyin: "caodi", meaning: "lawn; grass field" },
  { word: "办", pinyin: "ban", meaning: "to hold; to organize; to handle" },
  { word: "晴天", pinyin: "qingtian", meaning: "sunny day" },
  { word: "野餐", pinyin: "yecan", meaning: "picnic; to picnic" },
  { word: "餐", pinyin: "can", meaning: "meal" },
  { word: "露营", pinyin: "luying", meaning: "camping; to camp" },
  { word: "云", pinyin: "yun", meaning: "cloud" },
  { word: "躺", pinyin: "tang", meaning: "to lie down" },
  { word: "星星", pinyin: "xingxing", meaning: "stars" },
  { word: "感觉", pinyin: "ganjue", meaning: "to feel; feeling" },
  { word: "轻松", pinyin: "qingsong", meaning: "relaxed; easy" },
  { word: "睡着", pinyin: "shuizhao", meaning: "to fall asleep" },
  { word: "阳光", pinyin: "yangguang", meaning: "sunlight" },
  { word: "香味", pinyin: "xiangwei", meaning: "fragrance; pleasant smell" },
  { word: "座", pinyin: "zuo", meaning: "classifier for buildings, mountains, large objects" },
  { word: "球场", pinyin: "qiuchang", meaning: "sports field; court" },
  { word: "游泳池", pinyin: "youyongchi", meaning: "swimming pool" },
  { word: "校友", pinyin: "xiaoyou", meaning: "alumni" },
  { word: "只要", pinyin: "zhiyao", meaning: "as long as; only need to" },
  { word: "请客", pinyin: "qingke", meaning: "to treat; to host a meal" },
  { word: "牛排", pinyin: "niupai", meaning: "steak" },
  { word: "红绿灯", pinyin: "honglvdeng", meaning: "traffic light" }
];

